name: formatter_server
description: >-
  Provides Formatting API for IDEs.
version: 0.9.0
issue_tracker: https://github.com/xnfo-dart/formatter_server/issues
repository: https://github.com/xnfo-dart/formatter_server
environment:
  sdk: '>=2.17.0 <3.0.0'
publish_to: none

dependencies:
  args: ^2.3.1
  analyzer_plugin: ^0.11.1
  analyzer: '>=4.4.0 <6.0.0'
  _fe_analyzer_shared: any #analyzer will decide wich one to use.
  xnfo_formatter:
    path: ../xnfo_formatter #change to git when uploaded

dev_dependencies:
  grinder: ^0.9.2
  html: ^0.15.0
  lints: ^2.0.0
  package_config: ^2.1.0
  test: ^1.16.0
  yaml: ">=2.0.0 <4.0.0"

executables:
  dartcfmtd: listen

platforms:
  linux:
  macos:
  windows:
