name: formatter_server
description: >-
  Provides Formatting API for IDEs. (uses dart_polisher as formatter)
version: 0.9.3
issue_tracker: https://github.com/xnfo-dart/formatter_server/issues
repository: https://github.com/xnfo-dart/formatter_server
environment:
  sdk: '>=3.0.0 <4.0.0'
publish_to: none # Not intended to be published.

dependencies:
  args: ^2.3.1
  analyzer_plugin: ^0.11.1
  analyzer: '>=4.4.0 <6.0.0'
  _fe_analyzer_shared: any #analyzer will decide wich one to use.
  dart_polisher:
    git:
      url: https://github.com/xnfo-dart/dart_polisher.git
      ref: stable

#dependency_overrides:
#  dart_polisher:
#    path: ../dart_polisher #change to git when uploaded

dev_dependencies:
  grinder: ^0.9.2
#  html: ^0.15.0
  lints: ^2.0.0
  test: ^1.16.0
  test_reflective_loader: ^0.2.2
  yaml: ">=2.0.0 <4.0.0"
  analyzer_utilities:
    path: ./tool/protocol_spec/pkg/analyzer_utilities

executables:
  dartpolishd: listen

platforms:
  linux:
  macos:
  windows:
