include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - collection_methods_unrelated_type
    # Enable when we require Dart 2.19.0.
    #- dangling_library_doc_comments
    - depend_on_referenced_packages
    - implicit_call_tearoffs
    - library_annotations
    - unawaited_futures
    - unnecessary_library_directive
    - unnecessary_parenthesis
    - unreachable_from_main
