include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: false

linter:
  rules:
    - empty_constructor_bodies
    - empty_statements
    - unnecessary_brace_in_string_interps
    - valid_regexps
