name: Build binaries on tag

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

  # Allows you to run this workflow manually from the Actions tab (for testing)
  workflow_dispatch:

# run action will be from this dir
defaults:
  run:
    working-directory: ./formatter_server

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on:  ${{ matrix.os }}
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: dartpolishd
            osname: linux
          - os: macOS-latest
            output-name: dartpolishd
            osname: mac
          - os: windows-latest
            output-name: dartpolishd.exe
            osname: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://github.com/actions/checkout
      - name: "Checkout local repository"
        uses: actions/checkout@v3
        with:
          path: formatter_server

      - name: "Checkout Local Dart Polisher package"
        uses: actions/checkout@v3
        with:
          repository: xnfo-dart/dart_polisher
          path: dart_polisher
          token: ${{ secrets.GH_PAT }} # TODO: delete this line when going open source.
          ref: master

      # Uses https://github.com/dart-lang/setup-dart to get dart
      - name: "Dowload dart-sdk"
        uses: dart-lang/setup-dart@v1.3

      - name: Install pub dependencies
        run: dart pub get

      # Build (TODO: create dart grinder task for this particular build method)
      - name: "Create build dir"
        run: |
          mkdir build
          mkdir build/${{ matrix.osname }}
      - name : "Compile"
        run: dart compile exe bin/listen.dart -v -o build/${{ matrix.osname }}/${{ matrix.output-name }}

      # https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - name: "Upload OS Artifacts"
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dartpolishd-${{ matrix.osname }}
          path: formatter_server/build/${{ matrix.osname }}
